name: CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML files
        run: |
          echo "Checking HTML files..."
          if ls *.html 1> /dev/null 2>&1; then
            echo "HTML files found ✅"
          else
            echo "No HTML files found ❌"
            exit 1
          fi
